### ISSUE TITLE
How can I get in touch with you?

### ISSUE THREAD

**Issue by FriendsGit** [networked-aframe/naf-nametag-solidjs#1]
Hello, Mr. Vincent Fretin. I would like to establish communication with you regarding the development of a project, and I am seeking your guidance in the construction domain.

**Comment by vincentfretin** [comment]
Hello, you can find me on discord I'm vincentfretin there.

**Comment by vincentfretin** [comment]
You can join me right now in this room https://allocola.com/r/MTEzNTk3/btp
